name: React Native Android CI

on:
  push:
    branches:
      - master

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install npm dependencies
        run: |
          npm install

  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install npm dependencies
        run: |
          npm install

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.34.0
        with:
          api-level: 30
          script: echo "Emulator started"

      - name: React Native Android Build APK
        uses: realabbas/Github-Actions-React-Native@v1.1.2
        with:
          name: react-native-android-build-apk

      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
